# Generated by Django 5.0.4 on 2024-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_body_post_url_remove_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
