# Generated by Django 5.0.4 on 2024-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_gemini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='extracurricular_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='skill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='workshops_certifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='url',
            field=models.URLField(),
        ),
    ]
